# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: SNAKE_ENV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Generate Snake
        uses: Platane/snk@v3.0.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.3
        with:
          branch: main
          message: 'Generate Contribution Snake'

